package io.spring.dataflow.sample.usagedetailsender;

import java.util.Random;
import java.util.function.Supplier;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class UsageDetailSender {

	private String[] users = {"user1", "user2", "user3", "user4", "user5"};

	// real UK addresses generated by https://www.doogal.co.uk/RandomAddresses.php
	private String[] addresses = {
		"13 Elthorne Road, London, NW9 8BH",
		"61 - 63 Western Road, Hockley, B18 7QD",
		"3 Toby Road, Lydd On Sea, TN29 9PG",
		"21 Tanners Court, St Martins Close, Norwich, NR3 3HB",
		"11 Whittleton Place, Great Yarmouth, NR30 4HS",
		"12 Van Mildert Road, Newton Aycliffe, DL5 5DS",
		"35 Westminster Way, Newcastle Upon Tyne, NE7 7YU",
		"Dalegarth, Oakdale Road, Haywards Heath, RH16 3NE",
		"Flat 38, Herbert Morrison House, Clem Attlee Court, London, SW6 7SZ",
		"Flat 3, Temple Court, Monument Hill, Weybridge, KT13 8RR",
		"22 Ormonde Road, Wokingham, RG41 2RB",
		"2 Pebble Cottage, The Street, Thurgarton, NR11 7PD",
		"22 Gower Road, Shaftesbury, SP7 8RU",
		"1 Plover Close, Hereford, HR2 7TS",
		"Craig Y Rhosan, Cilycwm, SA20 0TG",
		"48 Milton Road, Ware, SG12 0PZ",
		"2 Woolley Orchard, Bradford-On-Avon, BA15 1BU",
		"41 Crane Drive, Verwood, BH31 6QB"
	};

	/**
	 * - for why a Supplier is used for Source, see https://dataflow.spring.io/docs/feature-guides/streams/function-composition/#function-composition
	 *
	 */ 
	@Bean
	public Supplier<UsageDetail> sendEvents() {
		return () -> {
			UsageDetail usageDetail = new UsageDetail();
			usageDetail.setUserId(this.users[new Random().nextInt(5)]);
			usageDetail.setDuration(new Random().nextInt(300));
			usageDetail.setData(new Random().nextInt(700));
			usageDetail.setAddress(this.addresses[new Random().nextInt(18)]);

			return usageDetail;
		};
	}
}
